## Emits replay-viewer/dist/wire_constants.js: the handful of engine constants
## the chrome has to agree with. Generated from the Nim consts rather than
## hand-copied, so a change to the tick rate or the playback speeds cannot
## drift between the sim and the scrubber.
##
##   nim r --path:src tools/gen_wire_constants.nim > .../wire_constants.js

import std/strutils
import lantern/types

when isMainModule:
  var speeds: seq[string]
  for value in PlaybackSpeeds:
    speeds.add($value)
  echo "// generated by tools/gen_wire_constants.nim - do not edit"
  echo "window.LANTERN_WIRE = {"
  echo "  fps: ", TargetFps, ","
  # 0.5 is the fleet-wide replay-only half speed. It rides ahead of the
  # engine's integer PlaybackSpeeds: the worker paces it with a fractional
  # tick carry (static_replay_worker.js), the sim never sees it.
  echo "  speeds: [0.5, ", speeds.join(", "), "],"
  echo "  mapWidth: ", MapWidth, ","
  echo "  mapHeight: ", MapHeight, ","
  echo "  crateSize: ", CrateSize, ","
  echo "  gameVersion: \"", GameVersion, "\","
  echo "  protocol: \"", ReplayProtocol, "\""
  echo "};"
